# Generated by Django 6.1 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordchangelog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangelog',
            name='change_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('RESET', 'Password Reset')], max_length=10),
        ),
    ]
