"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-qgg!i5c--*s2+$prb^03b&gr*_h$f8t2w9#9j7%crn4vof&s3b"
)

DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",

    # Project apps
    "accounts",
    "hotels",
    "reviews",
    "bookings",
]


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {

    # Access token remains valid for 30 minutes.
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=30
    ),

    # Refresh token remains valid for 7 days.
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7
    ),
}


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = "config.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# DATABASE
# =========================================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.postgresql",

        "NAME":
            os.getenv("DB_NAME"),

        "USER":
            os.getenv("DB_USER"),

        "PASSWORD":
            os.getenv("DB_PASSWORD"),

        "HOST":
            os.getenv("DB_HOST"),

        "PORT":
            os.getenv("DB_PORT"),
    }
}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"


# ---------------------------------------------------------
# TIMEZONE CONFIGURATION
# ---------------------------------------------------------

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "static/"


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# EMAIL CONFIGURATION
# =========================================================
#
# Django 6.1 uses MAILERS for email configuration.
#
# BookingX uses email for:
#
# - Forgot password
# - Password reset links
# - Future account notifications
#
# SMTP credentials are stored in .env.
#
# Required .env variables:
#
# EMAIL_HOST
# EMAIL_PORT
# EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD
# EMAIL_USE_TLS
# DEFAULT_FROM_EMAIL
#
# FRONTEND_URL
#
# =========================================================

MAILERS = {

    "default": {

        "BACKEND":
            "django.core.mail.backends.smtp.EmailBackend",

        "OPTIONS": {

            "host":
                os.getenv(
                    "EMAIL_HOST",
                    "smtp.gmail.com"
                ),

            "port":
                int(
                    os.getenv(
                        "EMAIL_PORT",
                        "587"
                    )
                ),

            "username":
                os.getenv(
                    "EMAIL_HOST_USER"
                ),

            "password":
                os.getenv(
                    "EMAIL_HOST_PASSWORD"
                ),

            "use_tls":
                os.getenv(
                    "EMAIL_USE_TLS",
                    "True"
                ).lower() == "true",

            "timeout":
                10,
        },
    },
}


# =========================================================
# DEFAULT EMAIL SENDER
# =========================================================

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "BookingX <noreply@bookingx.com>"
)


# =========================================================
# FRONTEND URL
# =========================================================
#
# Django uses this when creating password reset links.
#
# Example:
#
# http://localhost:5173/reset-password/<uid>/<token>
#
# =========================================================

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173"
).rstrip("/")


# =========================================================
# CORS
# =========================================================
#
# BookingX React frontend runs on Vite.
#
# Both localhost and 127.0.0.1 are allowed because browsers
# treat them as different origins.
#
# =========================================================

CORS_ALLOWED_ORIGINS = [

    "http://localhost:5173",

    "http://127.0.0.1:5173",
]


# =========================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

