# Generated by Django 6.1 on 2026-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
